
#'@param sim A simulation object generated by run.model
#'@param years The years we want to plot
#'@param outcome The outcome to show. Choices for now are "prevalence" (the number of people with HIV who are aware of their diagnosis) or "new" (number of new diagnoses in a year)
#'
#'@return A ggplot object with years on the x-axis, and the outcome on the y-axis. MD Calibration data in dots, simulation projections in a line
simplot <- function(sim,
                    years,
                    outcome)
{
    
}